name: Build DEB Packages

on:
  release:
  push:
  workflow_dispatch:

jobs:
  build_x64:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Prepare build environment
        run: |
          sudo apt install git tar fakeroot libssl-dev libcap2-bin autoconf automake libtool build-essential

      - uses: actions/checkout@v3
        submodules: 'recursive'

      - name: Build Package
        run: |
          $GITHUB_WORKSPACE/build-config/debian/bin/make-deb
      
      - name: Create Artifact
        uses: actions/upload-artifact@v3
        with:
          name: atlas_software_probe_x64
          path: ./*.deb