# This is a basic workflow to help you get started with Actions

name: Sync with RIPE repo
on: 
  schedule:
    - cron: '0 0 * * *'
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch Upstream
        run: |
          git config --global user.name 'Github Actions' 
          git config --global user.email 'noreply@github.com'
          git remote add upstream https://github.com/RIPE-NCC/ripe-atlas-software-probe
          git fetch upstream master --tags
      - name: Merge
        run: git merge --ff-only upstream/master
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
